package Mts.Crud.Exceptions;

public enum ErrorCodes {

  ARTICLE_NOT_FOUND(100),
  ARTICLE_NOT_VALID(101),
  ARTICLE_ALREADY_IN_USE(102),

  CATEGORY_NOT_FOUND(200),
  CATEGORY_NOT_VALID(201),
  CATEGORY_ALREADY_IN_USE(202),

  CLIENT_NOT_FOUND(300),
  CLIENT_NOT_VALID(301),
  CLIENT_ALREADY_IN_USE(302),

  COMMANDE_CLIENT_NOT_FOUND(400),
  COMMANDE_CLIENT_NOT_VALID(401),
  COMMANDE_CLIENT_NON_MODIFIABLE(402),
  COMMANDE_CLIENT_ALREADY_IN_USE(403),

  COMMANDE_FOURNISSEUR_NOT_FOUND(500),
  COMMANDE_FOURNISSEUR_NOT_VALID(501),
  COMMANDE_FOURNISSEUR_NON_MODIFIABLE(502),
  COMMANDE_FOURNISSEUR_ALREADY_IN_USE(503),

  ENTREPRISE_NOT_FOUND(600),
  ENTREPRISE_NOT_VALID(601),

  FOURNISSEUR_NOT_FOUND(700),
  FOURNISSEUR_NOT_VALID(701),
  FOURNISSEUR_ALREADY_IN_USE(702),

  LIGNE_COMMANDE_CLIENT_NOT_FOUND(800),
  LIGNE_COMMANDE_FOURNISSEUR_NOT_FOUND(900),
  LIGNE_VENTE_NOT_FOUND(1000),

  MVT_STK_NOT_FOUND(1100),
  MVT_STK_NOT_VALID(1101),

  UTILISATEUR_NOT_FOUND(1200),
  UTILISATEUR_NOT_VALID(1201),
  UTILISATEUR_ALREADY_EXISTS(1202),
  UTILISATEUR_CHANGE_PASSWORD_OBJECT_NOT_VALID(1203),


  VENTE_NOT_FOUND(1300),
  VENTE_NOT_VALID(1301),
  VENTE_ALREADY_IN_USE(1302),

  // Liste des exception techniaues
  UPDATE_PHOTO_EXCEPTION(1400),
  UNKNOWN_CONTEXT(1401)
  ;

  private int code;

  ErrorCodes(int code) {
    this.code = code;
  }

  public int getCode() {
    return code;
  }
}
